### ISSUE TITLE
Add testing and CI for 1.0.0 release

### ISSUE THREAD

**Issue by mraible** [wi3land/ionic-appauth#138]
I created issues with $500 bug bounties for their implementation. I'd like to see these fixed before this library's 1.0 release.

- [Add tests](https://github.com/jhipster/generator-jhipster-ionic/issues/713) 
- [Add CI](https://github.com/jhipster/generator-jhipster-ionic/issues/714)

**Comment by amanganiello90** [comment]
Hi @mraible .
I go ahead with **ts-mockito**, **mocha**, and **nyc for coverage reports**, as you can see on : https://github.com/wi3land/ionic-appauth/compare/master...amanganiello90:ionic-appauth:feature/test-issue-138

I have also added the task in the two github actions.

The following is the report with 3 tests:

![test report](https://user-images.githubusercontent.com/20536757/229151277-337cc173-a0c8-48f5-81d1-0467358a6dd0.png)


I'd like to know your opinion and if it is all well, in order to continue this task.
Thanks.

**Comment by mraible** [comment]
@amanganiello90 Looks good! My only comments are related to syntax: can you please use single quotes for imports and indent two spaces for JSON, JS, and TS files?

**Comment by amanganiello90** [comment]
@mraible yes,
I have added a prettier task with that rules: https://github.com/wi3land/ionic-appauth/compare/master...amanganiello90:ionic-appauth:feature/test-issue-138

So all files are formatted

**Comment by amanganiello90** [comment]
Hi @mraible,
I have created a PR with the feature described on https://github.com/wi3land/ionic-appauth/pull/203 

The coverage report is the following:
![coverage](https://user-images.githubusercontent.com/20536757/232841318-22697c7e-74ec-442b-8a23-0fbf253543c1.png)

I have mocked all external and plugin classes using some mock libraries, but the only the cordova classes are not mockable.
The reason is that **SecureStorage Cordova plugin** is not for commonJS module and in mocha test arises typescript errors.
However I have mocked with success Capacitor plugins, so the coverage is high.

Give me feedback if it is all done (CI and tests).

Thank you very much!!
