### ISSUE TITLE
Unable to find AuthService

### ISSUE THREAD

**Issue by awadeyar** [wi3land/ionic-appauth#6]
I have ran this command _

> "npm install ionic-appauth --save"

but unable to find the AuthService service. Then i referred your cordova demo 

> "https://github.com/wi3land/ionic-appauth-ng-demo" but unable to follow how npm install add the **core** module and **implicit** component.

**Comment by wi3land** [comment]
@awadeyar The AuthService has to be built into your application using the ionic-appauth-ng-demo as a guide. 'IonicAuth' class is in the npm package but you need to inherit from it to make the auth service.

This is because the npm package isn't Angular specific, it is being built out to also support react and vue.

**Comment by wi3land** [comment]
I am going to close this issue as it is more of a misunderstanding, if you need any further help just reach out.
